[project]
name = "rnd-testtask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
    "tabulate>=0.10.0",
]

[dependency-groups]
dev = [
    "marimo>=0.24.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["rnd_test_task*"]

[project.scripts]
app = "rnd_test_task.cli:main"
